server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://3.38.101.12:3306/kongs?useSSL=false&allow
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        show_sql: true
    default_batch_fetch_size: 1000
